### PR TITLE
Integration test

### PR DESCRIPTION
**Pull request by Eternalgratis**
- [ ] Use Capybara to write integration tests for each view in your project.
- [ ] User index page
- [ ] user show page:
- [ ] User post index page
- [ ] Post show page

### CODE REVIEW

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @Eternalgratis, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

768070f3-bc9a-4aba-b8bc-25793e00ea1e_text

## Highlights
✔️ All linters passing
✔️ Correct Gitflow
✔️ Professional Readme

## Required 
- [ ] Kindly make sure that all tests pass, currently, some are failing. Also, nothing is seen on the browser.

Screenshot 2022-11-09 at 12 33 11 AM

https://user-images.githubusercontent.com/70269507/200681103-27d791cc-cabb-472d-8962-394f2576421b.mov

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Eternalgratis** [comment]
Hi @sja-thedude ,
Thank you for the review. However, that's not the case at my end. All my test are passing and the view is showing correctly. Below are the screenshots of their functionalities
Integraton-test1
integraton-test2


integrated-test3

**Comment by sja-thedude** [comment]
Hi @Eternalgratis,

I am running all the tests with rspec. Could you run this and let me know if all are passing ?

**Comment by MahmoudBakr23** [comment]
Hi @sja-thedude, thank you for your review ❤️ I'm here to let you know that you're running the tests for all of the spec folders. However, this project dictates only integration tests that @Eternalgratis implemented in spec/features so they're 25 examples of all success. I hope this clarifies things for both of you 😄

**Comment by MahmoudBakr23** [comment]
Hi @Eternalgratis 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

**Highlights**
- Nicely done with the integration tests so far
- Great communication

Cheers and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by MahmoudBakr23 — APPROVED** [review]
Hi @Eternalgratis 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

**Highlights**
- Nicely done with the integration tests so far
- Great communication

Cheers and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
